"""Initial migration

Revision ID: 68df30f530b4
Revises: 
Create Date: 2025-05-27 18:10:44.454701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68df30f530b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 