"""Create tables for tracks, jobs, and transitions

Revision ID: d0d6ed78beeb
Revises: 68df30f530b4
Create Date: 2025-05-28 00:11:10.736938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d6ed78beeb'
down_revision = '68df30f530b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 