"""Add beat analysis fields to tracks table

Revision ID: f2ff23da73e9
Revises: d787594d0323
Create Date: 2025-06-03 02:30:49.462018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ff23da73e9'
down_revision = 'd787594d0323'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('beat_timestamps', sa.JSON(), nullable=True))
    op.add_column('tracks', sa.Column('beat_intervals', sa.JSON(), nullable=True))
    op.add_column('tracks', sa.Column('beat_confidence', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('beat_confidence_scores', sa.JSON(), nullable=True))
    op.add_column('tracks', sa.Column('beat_regularity', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('average_beat_interval', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'average_beat_interval')
    op.drop_column('tracks', 'beat_regularity')
    op.drop_column('tracks', 'beat_confidence_scores')
    op.drop_column('tracks', 'beat_confidence')
    op.drop_column('tracks', 'beat_intervals')
    op.drop_column('tracks', 'beat_timestamps')
    # ### end Alembic commands ### 